/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KeyBoardFrame.java
 *
 * Created on Apr 7, 2014, 2:30:17 PM
 */
package com.keyboard;

import com.generic.utils.utils;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JComponent;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Yusuf
 */
public class KeyBoardFrame extends javax.swing.JFrame {

    /** Creates new form KeyBoardFrame */
    public KeyBoardFrame() {
        initComponents();
    }

    public void createView() {
        kv.setParentjf(this);
        kv.setParentPanel(jPanel1);
        kv.createView();


    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        if (b) {
            createView();
            autoLocate(utils.last_textbox);

        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void autoLocate(JComponent txt) {
        if (!isVisible()) {
            return;
        }
        if (txt == null) {
            setLocationRelativeTo(null);
        }
        double sw = Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        double sh = Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        int nx = txt.getLocationOnScreen().x;
        int ny = txt.getLocationOnScreen().y + txt.getHeight() + 30;
        int ny1 = ny + getHeight() + 30;
        int nx1 = nx + getWidth();
        if (ny1 > sh) {
            if (nx1 > sw) {
                nx = nx - getWidth();
            }
            ny = ny - (txt.getHeight() + getHeight() + 30);
        }
        /*
        if (ny + getWidth() < Toolkit.getDefaultToolkit().getScreenSize().getWidth()) {
        ny = ny - getWidth() - 5;
        }
        if (nx + getHeight() < Toolkit.getDefaultToolkit().getScreenSize().getHeight()) {
        nx = nx - (getHeight() + txt.getHeight() + 2);
        }
         * 
         */ {
            setLocation(nx, ny);
            setFocusableWindowState(false);
            toFront();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private keyboardViewer kv = new keyboardViewer(jPanel1);
}
