/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reportPanel.java
 *
 * Created on 02/05/2010, 12:56:46 م
 */
package com.forms.panels;

import ar.com.fdvs.dj.core.DynamicJasperHelper;
import ar.com.fdvs.dj.core.layout.ClassicLayoutManager;
import ar.com.fdvs.dj.domain.DJCalculation;
import ar.com.fdvs.dj.domain.DynamicReport;
import ar.com.fdvs.dj.domain.builders.ColumnBuilder;
import ar.com.fdvs.dj.domain.builders.DynamicReportBuilder;
import ar.com.fdvs.dj.domain.builders.GroupBuilder;
import ar.com.fdvs.dj.domain.constants.GroupLayout;
import ar.com.fdvs.dj.domain.entities.DJGroup;
import ar.com.fdvs.dj.domain.entities.columns.AbstractColumn;
import ar.com.fdvs.dj.domain.entities.columns.PropertyColumn;
import com.forms.MainFrame;
import com.generic.model.DBClass;
import com.generic.model.dataCell;
import com.generic.model.localTableModel;
import com.generic.model.qryColumn;
import com.generic.utils.DynamicReportSetting;
import com.generic.utils.Parameter;
import com.generic.utils.QueryExe;
import com.generic.utils.XTableColumnModel;
import com.generic.utils.utils;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import java.io.FileInputStream;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRField;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author yusuf
 */
public class reportPanel extends javax.swing.JPanel {

    private javax.swing.table.DefaultTableModel dfltmodel = new javax.swing.table.DefaultTableModel();

    /** Creates new form reportPanel */
    public reportPanel() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel15 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        listReports = new javax.swing.JList();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        pnl_main = new javax.swing.JPanel();
        pnlParas1 = new javax.swing.JPanel();
        pnl_paras = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt2Date = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt3Date = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        listDriver = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txt4Date = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtReportfilter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        cmdOpenVou = new javax.swing.JButton();
        cmdReprint = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtSum = new javax.swing.JLabel();

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 16));

        jSplitPane1.setDividerLocation(250);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        listReports.setFont(new java.awt.Font("Tahoma", 0, 18));
        listReports.setModel(new DefaultListModel());
        listReports.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listReportsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listReports);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jComboBox1, 0, 249, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel15);

        jPanel16.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jButton14.setText("Query");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton14);

        jButton15.setText("Preview");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton15);

        jButton16.setText("Print");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton16);

        pnl_main.setLayout(new java.awt.GridLayout(1, 2));

        pnlParas1.setLayout(new java.awt.BorderLayout());

        pnl_paras.setLayout(new java.awt.GridBagLayout());
        pnlParas1.add(pnl_paras, java.awt.BorderLayout.NORTH);

        pnl_main.add(pnlParas1);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        pnl_main.add(jPanel17);

        jScrollPane5.setViewportView(pnl_main);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel14);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reports", jPanel13);

        jLabel1.setText("Date of Sales");

        txt2Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2DateActionPerformed(evt);
            }
        });
        txt2Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt2DateFocusLost(evt);
            }
        });

        jButton2.setText("Show Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt2Date, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(618, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt2Date, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(358, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Net Sales Summary", jPanel2);

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.setRowHeight(25);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        jPanel11.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabel2.setText("Date of Sales");
        jPanel11.add(jLabel2);

        txt3Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt3DateFocusLost(evt);
            }
        });
        jPanel11.add(txt3Date);

        jButton4.setText("Show Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton4);

        jButton7.setText("Print");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton7);

        jPanel12.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButton8.setText("Open voucher");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton8);

        jButton13.setText("Print Voucher");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton13);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Net sales Details", jPanel3);

        jPanel9.setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Driver/Cashier");
        jPanel9.add(jLabel8);

        listDriver.setModel(new javax.swing.DefaultComboBoxModel(new dataCell[] { new dataCell("","") }));
        listDriver.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel9.add(listDriver);

        jLabel3.setText("Date:");
        jPanel9.add(jLabel3);

        txt4Date.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt4DateFocusLost(evt);
            }
        });
        jPanel9.add(txt4Date);

        jButton12.setText("Print Voucher");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton12);

        jButton9.setText("Show Details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton9);

        jButton10.setText("Preview");
        jPanel9.add(jButton10);

        jButton11.setText("Pay Selected Inv");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton11);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.setRowHeight(25);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Outstanding Collection", jPanel6);

        jPanel8.setAlignmentX(0.0F);
        jPanel8.setAlignmentY(0.0F);
        jPanel8.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jPanel8.add(txtReportfilter);

        jButton1.setText("Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1);

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3);

        jButton6.setText("Main Screen");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6);

        cmdOpenVou.setText("Open Voucher");
        cmdOpenVou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOpenVouActionPerformed(evt);
            }
        });
        jPanel8.add(cmdOpenVou);

        cmdReprint.setText("Re-Print Voucher");
        cmdReprint.setMargin(new java.awt.Insets(2, 0, 2, 0));
        cmdReprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReprintActionPerformed(evt);
            }
        });
        jPanel8.add(cmdReprint);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Store balance report", jPanel1);

        txtSum.setBackground(java.awt.Color.yellow);
        txtSum.setFont(new java.awt.Font("Tahoma", 0, 18));
        txtSum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtSum.setText("Total : ");
        txtSum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSum.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtSum, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(txtSum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt2DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt2DateFocusLost
        try {
            txt2Date.setText(sdf.format(sdf.parse(txt2Date.getText())));
        } catch (ParseException ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
            txt2Date.requestFocus();
        }
}//GEN-LAST:event_txt2DateFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tbModel.setDynamicFilter(txtReportfilter.getText());
            jTable1.updateUI();
            txtReportfilter.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {
            String reportSource = "reports/rpt_store_balance.jrxml";
            String reportDest = "reports/output/rpt_store_balance.html";
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("COMPANY_NAME", parentJf.getMapVars().get("COMPANY_NAME"));
            params.put("FILTERTEXT", txtReportfilter.getText());
            params.put("REPORT_DATETIME", new Timestamp(System.currentTimeMillis()));
            params.put("USERNAME", parentJf.getLp().getLogon_user());
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, dbc.getDbConnection()); //new JREmptyDataSource());
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);

            JasperPrintManager.printReport(jasperPrint, false);
        } catch (Exception ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        //JasperViewer.viewReport(jasperPrint, false);

    }//GEN-LAST:event_jButton3ActionPerformed
    public void open_vou() {
        if (Double.valueOf(tbModel.getFieldValue(jTable1.getSelectedRow(), "AMOUNT").toString()) > 0) {
            String s = tbModel.getFieldValue(jTable1.getSelectedRow(), "KEYFLD").toString();
            parentJf.getSp().load_data(s);
            parentJf.getCmdSales().doClick();
        } else {
            String s = tbModel.getFieldValue(jTable1.getSelectedRow(), "KEYFLD").toString();

            parentJf.getCmdReturn().doClick();
            parentJf.getSpr().load_data(s);
            parentJf.getCmdReturn().doClick();

        }
    }

    public void print_vou() {
        if (Double.valueOf(tbModel.getFieldValue(jTable1.getSelectedRow(), "AMOUNT").toString()) > 0) {
            String s = tbModel.getFieldValue(jTable1.getSelectedRow(), "KEYFLD").toString();
            parentJf.getSp().print_data(Double.valueOf(s));
        }


    }
    private void txt3DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt3DateFocusLost
        try {
            txt3Date.setText(sdf.format(sdf.parse(txt3Date.getText())));
        } catch (ParseException ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
            txt3Date.requestFocus();
        }

}//GEN-LAST:event_txt3DateFocusLost

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        getDataStoreBalance();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void txt2DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2DateActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getSalesDetailsQuery();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            String reportSource = "reports/rpt_net_sales_details.jrxml";
            String reportDest = "reports/output/rpt_net_sales_details.html";
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("COMPANY_NAME", parentJf.getMapVars().get("COMPANY_NAME"));
            params.put("LOCATIONCODE", parentJf.getMapVars().get("DEFAULT_LOCATION"));
            params.put("TODATE", new Timestamp(sdf.parse(txt3Date.getText()).getTime()));
            params.put("USERNAME", parentJf.getLp().getLogon_user());
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, dbc.getDbConnection()); //new JREmptyDataSource());
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperPrintManager.printReport(jasperPrint, false);
        } catch (Exception ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        open_vou();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txt4DateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt4DateFocusLost
        try {
            txt4Date.setText(sdf.format(sdf.parse(txt4Date.getText())));
        } catch (ParseException ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
            txt4Date.requestFocus();
        }

    }//GEN-LAST:event_txt4DateFocusLost

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            String s = tbModel.getFieldValue(jTable1.getSelectedRow(), "KEYFLD").toString();
            String i = tbModel.getFieldValue(jTable1.getSelectedRow(), "KEYFLD").toString();
            dbc.getDbConnection().setAutoCommit(false);
            utils.execSql("update pospur1 set paidamt2=((inv_amt+add_charge)-disc_amt) where keyfld=" + s, dbc.getDbConnection());
            dbc.getDbConnection().commit();
            JOptionPane.showMessageDialog(parentJf, "Paid Successed for # " + i);
            getOutstandingColl();
        } catch (SQLException ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(parentJf, ex.getMessage());
            try {
                dbc.getDbConnection().rollback();
            } catch (SQLException ex1) {
                Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        getOutstandingColl();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        print_vou();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        print_vou();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
            printReport(((dataCell) listReports.getSelectedValue()).getValue().toString());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(parentJf, ex.getMessage());
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void listReportsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listReportsValueChanged
        try {
            String repid = ((dataCell) listReports.getSelectedValue()).getValue().toString();
            show_params(repid);
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(parentJf, ex);
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listReportsValueChanged

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        execQuery();
        jTabbedPane1.setSelectedComponent(jPanel1);

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getSalesQuery();
        txt2Date.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String reportSource = "reports/rpt_net_sales_sum.jrxml";
            String reportDest = "reports/output/rpt_net_sales_sum.html";
            Map<String, Object> params = new HashMap<String, Object>();
            params.put("COMPANY_NAME", parentJf.getMapVars().get("COMPANY_NAME"));
            params.put("LOCATIONCODE", parentJf.getMapVars().get("DEFAULT_LOCATION"));
            params.put("TODATE", new Timestamp(sdf.parse(txt2Date.getText()).getTime()));
            params.put("USERNAME", parentJf.getLp().getLogon_user());
            JasperReport jasperReport = JasperCompileManager.compileReport(reportSource);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, params, dbc.getDbConnection()); //new JREmptyDataSource());
            JasperExportManager.exportReportToHtmlFile(jasperPrint, reportDest);
            JasperPrintManager.printReport(jasperPrint, false);
        } catch (Exception ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton5ActionPerformed

    private void cmdOpenVouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOpenVouActionPerformed
        open_vou();
    }//GEN-LAST:event_cmdOpenVouActionPerformed

    private void cmdReprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReprintActionPerformed
        print_vou();
    }//GEN-LAST:event_cmdReprintActionPerformed

    public void show_params(String repid) throws SQLException {
        listParas.clear();
        pnl_paras.removeAll();
        pnl_paras.updateUI();
        PreparedStatement pst = dbc.getDbConnection().prepareStatement("select PARAM_NAME, PARA_TYPE, PARA_DEFAULT, PARA_DESCR, PARA_LIST, PARA_LABEL,MAX(POS) POS from pos_reps_paras "
                + "where (repid=? OR 'ALL'=?)  GROUP BY PARAM_NAME, PARA_TYPE, PARA_DEFAULT, PARA_DESCR, PARA_LIST, PARA_LABEL ORDER BY POS", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        pst.setString(1, repid);
        pst.setString(2, repid);
        ResultSet rst = pst.executeQuery();
        rst.beforeFirst();
        while (rst.next()) {
            Parameter pm = new Parameter(rst.getString("PARAM_NAME"), rst.getString("PARA_DEFAULT"));
            String strStore = "";
            if (mapDefaultParas.get(pm.getName().toUpperCase()) != null) {
                strStore = mapDefaultParas.get(pm.getName().toUpperCase());
            }
            if (rst.getString("PARA_TYPE").equalsIgnoreCase("VARCHAR2")) {
                pm.setValueType(Parameter.DATA_TYPE_STRING);
            }
            if (rst.getString("PARA_TYPE").equalsIgnoreCase("DATE")) {
                pm.setValueType(Parameter.DATA_TYPE_DATE);
            }
            if (rst.getString("PARA_TYPE").equalsIgnoreCase("NUMBER")) {
                pm.setValueType(Parameter.DATA_TYPE_NUMBER);
            }

            if (rst.getString("PARA_LIST") != null && !rst.getString("PARA_LIST").isEmpty()) {
                pm.setLovsql(rst.getString("PARA_LIST"));
            }

            if (strStore.length() == 0 && rst.getString("PARA_DEFAULT").startsWith("#")) {
                pm.setValue(parentJf.getMapVars().get(rst.getString("PARA_DEFAULT").substring(1)));
            }

            if (strStore.length() == 0 && rst.getString("PARA_DEFAULT").startsWith("$TODAY")) {
                SimpleDateFormat sdf = new SimpleDateFormat(utils.FORMAT_SHORT_DATE);
                pm.setValue(new Date(System.currentTimeMillis()));
            }

            if (strStore.length() > 0) {
                try {
                    if (pm.getValueType().equals(Parameter.DATA_TYPE_DATE)) {
                        SimpleDateFormat sdf = new SimpleDateFormat(utils.FORMAT_SHORT_DATE);
                        pm.setValue(sdf.parse(strStore));
                    }
                    if (pm.getValueType().equals(Parameter.DATA_TYPE_NUMBER)) {
                        NumberFormat nf = NumberFormat.getInstance();
                        pm.setValue(nf.parse(strStore));
                    }
                    if (pm.getValueType().equals(Parameter.DATA_TYPE_STRING)) {
                        pm.setValue(strStore);
                    }
                } catch (ParseException ex) {
                    ex.printStackTrace();
                }

            }

            pm.setDescription(rst.getString("PARA_LABEL"));
            listParas.add(pm);
        }
        GridBagConstraints gc = new GridBagConstraints();
        int i = 0;
        for (Iterator<Parameter> it = listParas.iterator(); it.hasNext();) {
            final Parameter pm = it.next();
            String s = "";
            if (pm.getValue() != null) {
                s = pm.getValue().toString();
            }
            final JLabel lb = new JLabel(pm.getDescription());

            gc.gridx = 0;
            gc.gridy = i;
            gc.insets = new Insets(10, 10, 10, 10);
            gc.gridwidth = 1;
            gc.weightx = 0.0;
            gc.fill = GridBagConstraints.HORIZONTAL;
            pnl_paras.add(lb, gc);

            if (!pm.getLovsql().isEmpty()) {
                final JComboBox tf = new JComboBox();
                utils.fillComboBox(tf, null, pm.getLovsql(), dbc.getDbConnection());
                gc.gridx = 1;
                gc.gridy = i++;
                gc.insets = new Insets(10, 10, 10, 10);
                pnl_paras.add(tf, gc);
                if (pm.getValue() != null) {
                    tf.setSelectedItem(utils.findByValue(tf, pm.getValue().toString()));
                }
                tf.addFocusListener(new FocusListener() {

                    public void focusGained(FocusEvent e) {
                    }

                    public void focusLost(FocusEvent e) {
                        pm.setValue(((dataCell) tf.getSelectedItem()).getValue().toString());
                        mapDefaultParas.put(pm.getName().toUpperCase(), pm.getValue().toString());
                    }
                });
                tf.addActionListener(new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        pm.setValue(((dataCell) tf.getSelectedItem()).getValue().toString());
                        mapDefaultParas.put(pm.getName().toUpperCase(), pm.getValue().toString());
                    }
                });
            } else {
                final JTextField tf = new JTextField(s);
                pm.setUIObject(tf);
                tf.setColumns(20);
                tf.addFocusListener(new FocusListener() {

                    public void focusGained(FocusEvent e) {
                    }

                    public void focusLost(FocusEvent e) {

                        if (pm.getValueType().equals(Parameter.DATA_TYPE_DATE)) {
                            SimpleDateFormat df = new SimpleDateFormat(utils.FORMAT_SHORT_DATE);

                            try {
                                Date d = df.parse(tf.getText());
                                tf.setText(df.format(d));
                                pm.setValue(df.parse(tf.getText()));
                                mapDefaultParas.put(pm.getName().toUpperCase(), tf.getText());
                            } catch (ParseException ex) {
                                ex.printStackTrace();
                                JOptionPane.showMessageDialog(parentJf, ex);
                                tf.requestFocus();
                            }
                        }
                        if (pm.getValueType().equals(Parameter.DATA_TYPE_NUMBER)) {
                            try {
                                NumberFormat df = NumberFormat.getInstance();
                                Number d = df.parse(tf.getText());
                                tf.setText(df.format(d));
                                pm.setValue(df.parse(tf.getText()));
                                mapDefaultParas.put(pm.getName().toUpperCase(), tf.getText());
                            } catch (ParseException ex) {
                                ex.printStackTrace();
                                JOptionPane.showMessageDialog(parentJf, ex);
                                tf.requestFocus();
                            }

                        }
                        if (pm.getValueType().equals(Parameter.DATA_TYPE_STRING)) {
                            pm.setValue(tf.getText());
                            mapDefaultParas.put(pm.getName().toUpperCase(), tf.getText());
                        }
                    }
                });


                tf.addActionListener(new ActionListener() {

                    public void actionPerformed(ActionEvent e) {

                        if (pm.getValueType().equals(Parameter.DATA_TYPE_DATE)) {
                            SimpleDateFormat df = new SimpleDateFormat(utils.FORMAT_SHORT_DATE);

                            try {
                                Date d = df.parse(tf.getText());
                                tf.setText(df.format(d));
                                pm.setValue(df.parse(tf.getText()));
                                mapDefaultParas.put(pm.getName().toUpperCase(), tf.getText());
                            } catch (ParseException ex) {
                                ex.printStackTrace();
                                JOptionPane.showMessageDialog(parentJf, ex);
                                tf.requestFocus();
                            }
                        }
                        if (pm.getValueType().equals(Parameter.DATA_TYPE_NUMBER)) {
                            try {
                                NumberFormat df = NumberFormat.getInstance();
                                Number d = df.parse(tf.getText());
                                tf.setText(df.format(d));
                                pm.setValue(df.parse(tf.getText()));
                                mapDefaultParas.put(pm.getName().toUpperCase(), tf.getText());
                            } catch (ParseException ex) {
                                ex.printStackTrace();
                                JOptionPane.showMessageDialog(parentJf, ex);
                                tf.requestFocus();
                            }

                        }
                        if (pm.getValueType().equals(Parameter.DATA_TYPE_STRING)) {
                            pm.setValue(tf.getText());
                            mapDefaultParas.put(pm.getName().toUpperCase(), tf.getText());
                        }
                    }

                    ;
                });

                gc.gridx = 1;
                gc.gridy = i++;
                gc.insets = new Insets(10, 10, 10, 10);
                pnl_paras.add(tf, gc);
                if (pm.getValue() != null) {
                    if (pm.getValueType().equals(Parameter.DATA_TYPE_DATE)) {
                        SimpleDateFormat df = new SimpleDateFormat(utils.FORMAT_SHORT_DATE);
                        tf.setText(df.format((Date) pm.getValue()));
                    } else {
                        tf.setText(pm.getValue().toString());
                    }

                }
            }

            pnl_paras.updateUI();

        }
    }

    public void customIntialize(MainFrame mf) {
        if (dbc == null) {
            try {
                parentJf = mf;
                jTable1.setColumnModel(new XTableColumnModel());
                dbc = tbModel.createDBClassFromConnection(parentJf.getDbConneciton());
                sdf = new SimpleDateFormat(parentJf.getMapVars().get("short_date_format"));
                decf = new DecimalFormat(parentJf.getMapVars().get("money_number"));
                txt2Date.setText(sdf.format(new java.util.Date(System.currentTimeMillis())));
                txt3Date.setText(sdf.format(new java.util.Date(System.currentTimeMillis())));
                txt4Date.setText(sdf.format(new java.util.Date(System.currentTimeMillis())));
                ((DefaultComboBoxModel) listDriver.getModel()).removeAllElements();
                ((DefaultComboBoxModel) listDriver.getModel()).addElement(new dataCell("", ""));
                PreparedStatement ps = dbc.getDbConnection().prepareStatement("select *from salesp where (type='S' or type='D') order by no", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                ResultSet rsx = ps.executeQuery();
                rsx.beforeFirst();
                while (rsx.next()) {
                    ((DefaultComboBoxModel) listDriver.getModel()).addElement(new dataCell(rsx.getString("name"), rsx.getString("NO")));
                }
                ps.close();
                rsx.close();

                loadList();
                //jTable1.setModel(tbModel);
                //tbModel.clearALl();
            } catch (SQLException ex) {
                Logger.getLogger(closeSalesPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void execQuery() {
        String repid = ((dataCell) listReports.getSelectedValue()).getValue().toString();
        execQuery(repid);
    }

    public void execQuery(String repid) {
        String sql = "";
        try {
            PreparedStatement ps1 = dbc.getDbConnection().prepareStatement("select *from pos_reps_header where repid='" + repid + "'", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs1 = ps1.executeQuery();
            if (!rs1.first()) {
                ps1.close();
                throw new SQLException("Can not load data for report,");
            }
            sql = rs1.getString("rep_sql");
            cmdOpenVou.setEnabled(false);
            cmdReprint.setEnabled(false);
            if (rs1.getString("OPEN_VOU").startsWith("Y")) {
                cmdOpenVou.setEnabled(true);
            }
            if (rs1.getString("REPRINT_VOU").startsWith("Y")) {
                cmdReprint.setEnabled(true);
            }

            ps1.close();
            QueryExe qe = new QueryExe(sql, dbc.getDbConnection());
            qe.getMapParas().clear();
            for (Iterator<Parameter> it = listParas.iterator(); it.hasNext();) {
                Parameter parameter = it.next();
                qe.getMapParas().put(parameter.getName(), parameter);
            }
            tbModel.clearALl();
            tbModel.appendRows(qe.convertRows());
            tbModel.getQrycols().addAll(qe.getColumnsList());
            tbModel.setAllColVisible(true);
            jTable1.getColumnModel().setColumnSelectionAllowed(false);
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setModel(dfltmodel);
            PreparedStatement pst = dbc.getDbConnection().prepareStatement("select *from POS_REP_COLS WHERE REPID='" + repid + "'", ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            ResultSet rstx = pst.executeQuery();
            rstx.beforeFirst();
            String sumtxt = "Sum : ";
            while (rstx.next()) {
                qryColumn qc = tbModel.getColByName(rstx.getString("COL_NAME"));
                if (qc != null) {
                    qc.setWidth(rstx.getInt("COLWIDTH"));
                    if (rstx.getString("COL_TITLE") != null) {
                        qc.setTitle(rstx.getString("COL_TITLE"));
                    }
                }


                if (qc != null && qc.isNumber() && rstx.getString("COL_FORMAT") != null) {
                    if (rstx.getString("COL_FORMAT").equals("MONEY_FORMAT")) {
                        qc.setNumberFormat(utils.FORMAT_MONEY);
                    }
                    if (rstx.getString("COL_FORMAT").equals("QTY_FORMAT")) {
                        qc.setNumberFormat(utils.FORMAT_QTY);
                    }
                    if (!rstx.getString("COL_FORMAT").equals("QTY_FORMAT") && !rstx.getString("COL_FORMAT").equals("MONEY_FORMAT")) {
                        qc.setNumberFormat(rstx.getString("COL_FORMAT"));
                    }
                }
                if (qc != null && qc.isDate() && rstx.getString("COL_FORMAT") != null) {
                    if (rstx.getString("COL_FORMAT").equals("SHORT_DATE_FORMAT")) {
                        qc.setDateFormat(utils.FORMAT_SHORT_DATE);
                    }
                    if (rstx.getString("COL_FORMAT").equals("LONG_DATE_FORMAT")) {
                        qc.setDateFormat(utils.FORMAT_LONG_DATE);
                    }
                    if (!rstx.getString("COL_FORMAT").equals("LONG_DATE_FORMAT") && !rstx.getString("COL_FORMAT").equals("SHORT_DATE_FORMAT")) {
                        qc.setDateFormat(rstx.getString("COL_FORMAT"));
                    }
                }
                if (qc != null && rstx.getString("COL_HIDE").startsWith("Y")) {
                    tbModel.getVisbleQrycols().remove(qc);
                }

                if (qc != null && rstx.getString("HAS_SUMMARY").startsWith("Y")) {
                    String vl = "";
                    if (!qc.getNumberFormat().isEmpty()) {
                        vl = (new DecimalFormat(qc.getNumberFormat())).format(tbModel.getSummaryOf(qc.getColname(), localTableModel.SUMMARY_SUM));
                    } else {
                        vl = String.valueOf(tbModel.getSummaryOf(qc.getColname(), localTableModel.SUMMARY_SUM));
                    }
                    sumtxt = sumtxt + qc.getColname() + " =  " + vl + ",";
                }

            }
            pst.close();
            txtSum.setText(sumtxt);
            jTable1.setModel(tbModel);
            tbModel.setEditAllowed(false);

            for (int colx = 0; colx
                    < jTable1.getModel().getColumnCount(); colx++) {
                jTable1.getColumnModel().getColumn(colx).setCellRenderer(new ColorRenderer(true));

            }
            jTable1.revalidate();
            jTable1.updateUI();

        } catch (SQLException ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(parentJf, ex.getMessage());
        }
    }

    public void printReport(String std) throws Exception {
        DynamicReportSetting st = new DynamicReportSetting();
        st.doStandard();
        int pf = 255;
        if (parentJf.getMapVars().get("REPORT_PAGE_WIDTH") != null) {
            pf = Integer.valueOf(parentJf.getMapVars().get("REPORT_PAGE_WIDTH"));
        }
        st.setPageWidth(pf);
        st.setIgnorePagination(true);
        st.setOrientation(DynamicReportSetting.CUSTOM_ORIENTATION);
        if (!std.equals("ALL")) {
            st.setTitle(listReports.getSelectedValue().toString());
            execQuery();
            printData(tbModel, st);
            return;
        } else {
            for (int i = 1; i < listReports.getModel().getSize(); i++) {
                dataCell dc = (dataCell) listReports.getModel().getElementAt(i);
                st.setTitle(dc.toString());
                String rep = (dc.getValue().toString());
                execQuery(rep);
                printData(tbModel, st);
            }
        }
    }

    public void printData(final localTableModel data, DynamicReportSetting reportSetting) throws Exception {
        String fl1 = "tmp";
        final String fl = fl1.replace("\\", "/");
        Map<String, String> parameter = new HashMap<String, String>();
        byte b[] = null;
        final JRDataSource jr = new JRDataSource() {

            private int irow = 0;

            public boolean next() throws JRException {
                irow++;
                if (irow > data.getRows().size()) {
                    return false;
                }
                return true;
            }

            public Object getFieldValue(JRField j) throws JRException {
                Object val = data.getFieldValue(irow - 1, j.getName());
                return val;
            }
        };

        // --------STYLES
        DynamicReportBuilder drb = new DynamicReportBuilder();
        Map<String, AbstractColumn> mapCols = new HashMap<String, AbstractColumn>();

        for (int i = 0; i < data.getVisbleQrycols().size(); i++) {
            String title = data.getVisbleQrycols().get(i).getTitle();
            String name = data.getVisbleQrycols().get(i).getColname();
            Integer width = data.getVisbleQrycols().get(i).getWidth();
            AbstractColumn col1 = ColumnBuilder.getNew().setColumnProperty(
                    name, String.class.getName()).setTitle(title).setWidth(
                    width).setFixedWidth(false).build();
            if (data.getVisbleQrycols().get(i).isNumber()) {
                col1 = ColumnBuilder.getNew().setColumnProperty(name,
                        BigDecimal.class.getName()).setTitle(title).build();
                if (data.getVisbleQrycols().get(i).getNumberFormat().length() > 0) {
                    col1.setPattern(data.getVisbleQrycols().get(i).getNumberFormat());
                    col1.setStyle(reportSetting.getStyleNumber());
                }
            }
            if (data.getVisbleQrycols().get(i).getDateFormat().length() > 0) {
                col1 = ColumnBuilder.getNew().setColumnProperty(name,
                        java.sql.Timestamp.class.getName()).setTitle(title).build();
                col1.setPattern(data.getVisbleQrycols().get(i).getDateFormat());
            }

            drb.addColumn(col1);
            if (data.getVisbleQrycols().get(i).isNumber()) {
                drb.addGlobalFooterVariable(col1, DJCalculation.SUM,
                        reportSetting.getStyleNumber2());
                drb.setGrandTotalLegend("Grand Total");
                drb.setGrandTotalLegendStyle(reportSetting.getStyleDetail());
            }
            mapCols.put(name, col1);
        }
        reportSetting.getListParams().clear();
        reportSetting.getListParams().addAll(listParas);

        reportSetting.wrapReport(drb, true);
        // GROUPING
        int cnt = 0;
        for (Iterator iterator = listGroupsBy.iterator(); iterator.hasNext();) {
            String fldname = (String) iterator.next();
            AbstractColumn col = mapCols.get(fldname);
            if (col == null) {
                mapCols.put(fldname, ColumnBuilder.getNew().setColumnProperty(
                        fldname, String.class.getName()).setTitle("").build());
                col = mapCols.get(fldname);
                drb.addColumn(mapCols.get(fldname));
            }
            col.setStyle(reportSetting.getStyleGroup());
            GroupBuilder grp = new GroupBuilder();
            grp.setCriteriaColumn((PropertyColumn) col);
            grp.setHeaderHeight(new Integer(30));
            if (cnt == 0) {
                for (int k = 0; k < listGroupSum.size(); k++) {
                    AbstractColumn numcol = mapCols.get(listGroupSum.get(k));
                    if (data.getColByName(listGroupSum.get(k)).isNumber()) {
                        grp.addFooterVariable(numcol, DJCalculation.SUM,
                                reportSetting.getStyleNumber2());
                    }
                }
            }
            grp.setGroupLayout(GroupLayout.VALUE_IN_HEADER);
            DJGroup g = grp.build();
            g.setDefaulHeaderVariableStyle(reportSetting.getStyleDetail());
            drb.addGroup(g);
            cnt++;
        }
        drb.setAllowDetailSplit(false);
        drb.setUseFullPageWidth(true);

        drb.setPrintColumnNames(true);
        DynamicReport dr = drb.build();
        DynamicJasperHelper.generateJRXML(dr, new ClassicLayoutManager(),
                parameter, "UTF-8", fl + ".jrxml");

        JasperPrint jp = DynamicJasperHelper.generateJasperPrint(dr, new ClassicLayoutManager(), jr);
        JasperPrintManager.printReport(jp, false);
    }

    public void getDataStoreBalance() {
        try {
            txtSum.setText("");
            jTabbedPane1.setSelectedIndex(0);
            tbModel.clearALl();
            tbModel.executeQuery("select i2.descr, s.refer,i.descr,(s.qty+(s.pos_in-s.pos_out)/i.pack) balance"
                    + " from stori s,items i,items i2 where i.reference=s.refer and i2.reference=i.parentitem and "
                    + " s.strno='" + parentJf.getMapVars().get("DEFAULT_STORE") + "'", true);
            tbModel.setEditAllowed(false);
            jTable1.getColumnModel().setColumnSelectionAllowed(false);
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setModel(dfltmodel);
            jTable1.setModel(tbModel);
            for (int colx = 0; colx
                    < jTable1.getModel().getColumnCount(); colx++) {
                jTable1.getColumnModel().getColumn(colx).setCellRenderer(new ColorRenderer(true));




            }
            jTable1.revalidate();
            jTable1.updateUI();











        } catch (SQLException ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(parentJf, ex.getMessage());
        }








    }

    public void getOutstandingColl() {
        String dno = ((dataCell) listDriver.getModel().getSelectedItem()).getValue().toString();

        try {

            txtSum.setText("");
            txt4Date.setText(sdf.format(sdf.parse(txt4Date.getText())));
            jTabbedPane1.setSelectedIndex(3);
            tbModel.clearALl();
            tbModel.executeQuery("select KEYFLD,INVOICE_NO,inv_ref Customer_Code,inv_refnm Customer_Name,INVOICE_DATE,"
                    + " DECODE(INVOICE_CODE,30,(inv_amt+ADD_CHARGE)-disc_amt,20,(((inv_amt+add_charge)-disc_amt)*-1)) AMOUNT,PAIDAMT2 PAID_AMOUNT "
                    + " from pospur1,INVOICETYPE "
                    + " where INVOICETYPE.NO=TYPE AND INVOICE_CODE IN (30,20) AND "
                    + " invoice_date=to_date('" + txt3Date.getText() + "','dd/mm/rrrr') AND "
                    + " POSPUR1.LOCATION_CODE=INVOICETYPE.LOCATION_CODE "
                    + " and POSPUR1.LOCATION_CODE='" + parentJf.getMapVars().get("DEFAULT_LOCATION") + "' "
                    + " and (pospur1.slsmn='" + dno + "' or '" + dno + "' is null) AND PAIDAMT2=0"
                    + " ORDER BY INVOICE_NO", true);
            tbModel.getColByName("AMOUNT").setNumberFormat(decf.toPattern());
            tbModel.getColByName("paid_amount").setNumberFormat(decf.toPattern());
            tbModel.getColByName("INVOICE_NO").setAlignmnet(JLabel.CENTER);
            tbModel.getColByName("KEYFLD").setVisible(false);
            tbModel.getVisbleQrycols().remove(tbModel.getColByName("KEYFLD"));
            tbModel.setEditAllowed(false);
            jTable1.getColumnModel().setColumnSelectionAllowed(false);
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setModel(dfltmodel);
            jTable1.setModel(tbModel);





            for (int colx = 0; colx
                    < jTable1.getModel().getColumnCount(); colx++) {
                jTable1.getColumnModel().getColumn(colx).setCellRenderer(new ColorRenderer(true));








            }

            jTable1.revalidate();
            jTable1.updateUI();





            double remain = tbModel.getSummaryOf("AMOUNT", localTableModel.SUMMARY_SUM) - tbModel.getSummaryOf("PAID_AMOUNT", localTableModel.SUMMARY_SUM);
            String amt = " Total := " + decf.format(tbModel.getSummaryOf("AMOUNT", localTableModel.SUMMARY_SUM));
            amt = amt + "       Paid Amount := " + decf.format(tbModel.getSummaryOf("PAID_AMOUNT", localTableModel.SUMMARY_SUM));
            amt = amt + "       BALANCE     := " + decf.format(remain);
            txtSum.setText(amt);













        } catch (Exception ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }










    }

    public void getSalesDetailsQuery() {
        try {
            txtSum.setText("");
            txt3Date.setText(sdf.format(sdf.parse(txt3Date.getText())));
            jTabbedPane1.setSelectedIndex(2);
            tbModel.clearALl();
            tbModel.executeQuery("select KEYFLD,INVOICE_NO,inv_ref Customer_Code,inv_refnm Customer_Name,INVOICE_DATE,"
                    + " DECODE(INVOICE_CODE,30,(inv_amt+ADD_CHARGE)-disc_amt,20,((inv_amt-disc_amt)*-1)) AMOUNT "
                    + " from pospur1,INVOICETYPE "
                    + " where INVOICETYPE.NO=TYPE AND INVOICE_CODE IN (30,20) AND "
                    + " invoice_date=to_date('" + txt3Date.getText() + "','dd/mm/rrrr') AND "
                    + " POSPUR1.LOCATION_CODE=INVOICETYPE.LOCATION_CODE "
                    + " and POSPUR1.LOCATION_CODE='" + parentJf.getMapVars().get("DEFAULT_LOCATION") + "' "
                    + " ORDER BY INVOICE_NO", true);
            tbModel.getColByName("AMOUNT").setNumberFormat(decf.toPattern());
            tbModel.getColByName("INVOICE_NO").setAlignmnet(JLabel.CENTER);
            tbModel.getColByName("KEYFLD").setVisible(false);
            tbModel.getVisbleQrycols().remove(tbModel.getColByName("KEYFLD"));
            tbModel.setEditAllowed(false);
            jTable1.getColumnModel().setColumnSelectionAllowed(false);
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setModel(dfltmodel);
            jTable1.setModel(tbModel);








            for (int colx = 0; colx
                    < jTable1.getModel().getColumnCount(); colx++) {
                jTable1.getColumnModel().getColumn(colx).setCellRenderer(new ColorRenderer(true));








            }


            jTable1.revalidate();
            jTable1.updateUI();

            txtSum.setText("Total : " + decf.format(tbModel.getSummaryOf("AMOUNT", localTableModel.SUMMARY_SUM)));













        } catch (Exception ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }









    }

    public void loadList() {
        try {
            PreparedStatement pst = dbc.getDbConnection().prepareStatement("select repid,repname from POS_REPS_HEADER order by repid", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rst = pst.executeQuery();
            rst.beforeFirst();




            ((DefaultListModel) listReports.getModel()).removeAllElements();




            ((DefaultListModel) listReports.getModel()).addElement(new dataCell("ALL", "ALL"));




            while (rst.next()) {
                dataCell dc = new dataCell(rst.getString("repname"), rst.getString("repid"));




                ((DefaultListModel) listReports.getModel()).addElement(dc);




            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(parentJf, ex);
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
        }









    }

    public void getSalesQuery() {
        try {
            txtSum.setText("");
            txt2Date.setText(sdf.format(sdf.parse(txt2Date.getText())));
            jTabbedPane1.setSelectedIndex(1);
            tbModel.clearALl();
            tbModel.executeQuery("select TYPE_NO TYPE,invoicetype.descr"
                    + ",sum((amount)*DECODE(INVOICE_CODE,20,-1,30,1)) AMOUNT "
                    + " from pospur1,INVOICETYPE,POSPAYMENTS "
                    + " where INVOICETYPE.NO=TYPE_NO AND INVOICE_CODE IN (30,20) AND VOU_KEYFLD=KEYFLD AND "
                    + " invoice_date=to_date('" + txt2Date.getText() + "','dd/mm/rrrr') "
                    + " and POSPUR1.LOCATION_CODE='" + parentJf.getMapVars().get("DEFAULT_LOCATION") + "'"
                    + " AND POSPUR1.LOCATION_CODE=INVOICETYPE.LOCATION_CODE "
                    + " GROUP BY INVOICETYPE.DESCR,TYPE_NO ORDER BY TYPE_NO", true);
            tbModel.setEditAllowed(false);
            jTable1.getColumnModel().setColumnSelectionAllowed(false);
            jTable1.getTableHeader().setReorderingAllowed(false);
            tbModel.getColByName("type").setAlignmnet(JLabel.CENTER);
            jTable1.setModel(dfltmodel);
            jTable1.setModel(tbModel);








            for (int colx = 0; colx
                    < jTable1.getModel().getColumnCount(); colx++) {
                jTable1.getColumnModel().getColumn(colx).setCellRenderer(new ColorRenderer(true));








            }
            tbModel.getColByName("AMOUNT").setNumberFormat(decf.toPattern());

            txtSum.setText("Total : " + decf.format(tbModel.getSummaryOf("AMOUNT", localTableModel.SUMMARY_SUM)));

            jTable1.revalidate();
            jTable1.updateUI();




















        } catch (Exception ex) {
            Logger.getLogger(reportPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(parentJf, ex.getMessage());
        }








    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdOpenVou;
    private javax.swing.JButton cmdReprint;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox listDriver;
    private javax.swing.JList listReports;
    private javax.swing.JPanel pnlParas1;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPanel pnl_paras;
    private javax.swing.JTextField txt2Date;
    private javax.swing.JTextField txt3Date;
    private javax.swing.JTextField txt4Date;
    private javax.swing.JTextField txtReportfilter;
    private javax.swing.JLabel txtSum;
    // End of variables declaration//GEN-END:variables
    private MainFrame parentJf = null;
    private localTableModel tbModel = new localTableModel();
    private DBClass dbc = null;
    private SimpleDateFormat sdf = null;
    private DecimalFormat decf = null;
    List<Parameter> listParas = new ArrayList<Parameter>();
    Map<String, String> mapDefaultParas = new HashMap<String, String>();
    private List<String> listGroupsBy = new ArrayList<String>();
    private List<String> listGroupSum = new ArrayList<String>();
}
