/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * closeReturnDlg.java
 *
 * Created on Apr 22, 2014, 6:24:28 PM
 */
package com.forms.panels;

import com.forms.MainFrame;
import com.generic.model.dataCell;
import com.keyboard.keyboardViewer;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Yusuf
 */
public class closeReturnDlg extends javax.swing.JDialog {

    public double sumPaidAmt = 0;
    public double sumNetAmt = 0;
    public double sumCashAmt = 0;
    public keyboardViewer kv = null;
    private DecimalFormat decimalformat = null;
    private SimpleDateFormat dateformat = null;
    private MainFrame parentJf = null;
    private double varCashType = -1;
    private String varSelText = "";
    public double sumGrossAmt = 0;

    /** Creates new form closeReturnDlg */
    public closeReturnDlg(java.awt.Frame parent, boolean modal) {



        super(parent, modal);

        initComponents();
        setLocationRelativeTo(null);
        setParentJf((MainFrame) parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        pnlSinglePay = new javax.swing.JPanel();
        sumTxtCashAmt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        sumTxtNetAmt = new javax.swing.JLabel();
        listType = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlParas1 = new javax.swing.JPanel();
        pnl_paras = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(-20561,true));

        sumTxtCashAmt.setFont(new java.awt.Font("Tahoma", 1, 24));
        sumTxtCashAmt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sumTxtCashAmt.setText("0");
        sumTxtCashAmt.setName("sumTxtCashAmt"); // NOI18N
        sumTxtCashAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumTxtCashAmtActionPerformed(evt);
            }
        });
        sumTxtCashAmt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sumTxtCashAmtsumTxtDiscAmtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sumTxtCashAmtsumTxtDiscAmtFocusLost(evt);
            }
        });

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Cash Given");

        sumTxtNetAmt.setBackground(new java.awt.Color(255, 255, 102));
        sumTxtNetAmt.setFont(new java.awt.Font("Tahoma", 1, 24));
        sumTxtNetAmt.setForeground(new java.awt.Color(0, 51, 204));
        sumTxtNetAmt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sumTxtNetAmt.setText("0.0");
        sumTxtNetAmt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));
        sumTxtNetAmt.setFocusTraversalPolicyProvider(true);
        sumTxtNetAmt.setOpaque(true);

        listType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTypeActionPerformed(evt);
            }
        });

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Pay Type");

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Net Amount");

        javax.swing.GroupLayout pnlSinglePayLayout = new javax.swing.GroupLayout(pnlSinglePay);
        pnlSinglePay.setLayout(pnlSinglePayLayout);
        pnlSinglePayLayout.setHorizontalGroup(
            pnlSinglePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSinglePayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSinglePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSinglePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listType, 0, 202, Short.MAX_VALUE)
                    .addComponent(sumTxtCashAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(sumTxtNetAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlSinglePayLayout.setVerticalGroup(
            pnlSinglePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSinglePayLayout.createSequentialGroup()
                .addGroup(pnlSinglePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumTxtNetAmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSinglePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlSinglePayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sumTxtCashAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/forms/panels/images/cancel.png"))); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/forms/panels/images/ok.png"))); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlParas1.setLayout(new java.awt.BorderLayout());

        pnl_paras.setLayout(new java.awt.GridBagLayout());
        pnlParas1.add(pnl_paras, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(pnlParas1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlSinglePay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlSinglePay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sumTxtCashAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumTxtCashAmtActionPerformed
        sumCashAmt = Double.valueOf(sumTxtCashAmt.getText());
        sumTxtCashAmt.setText(decimalformat.format(sumCashAmt));
}//GEN-LAST:event_sumTxtCashAmtActionPerformed

    private void sumTxtCashAmtsumTxtDiscAmtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sumTxtCashAmtsumTxtDiscAmtFocusGained
        //onfocusLostSums((JTextField) evt.getComponent());
}//GEN-LAST:event_sumTxtCashAmtsumTxtDiscAmtFocusGained

    private void sumTxtCashAmtsumTxtDiscAmtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sumTxtCashAmtsumTxtDiscAmtFocusLost
        sumCashAmt = Double.valueOf(sumTxtCashAmt.getText());
        sumTxtCashAmt.setText(decimalformat.format(sumCashAmt));
    }//GEN-LAST:event_sumTxtCashAmtsumTxtDiscAmtFocusLost

    private void listTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTypeActionPerformed
        sumCashAmt = sumNetAmt;
        sumTxtCashAmt.setText(decimalformat.format(sumNetAmt));
        sumTxtCashAmt.setEditable(false);
        if (listType.getSelectedItem() != null && (Double.valueOf(((dataCell) listType.getSelectedItem()).getValue().toString())) == varCashType) {
            sumTxtCashAmt.setEditable(true);
        }
}//GEN-LAST:event_listTypeActionPerformed
    private InputVerifier number_iv = new InputVerifier() {

        @Override
        public boolean verify(JComponent input) {
            JTextField txt = (JTextField) input;
            if (txt.getText().length() == 0) {
                return true;
            }

            boolean ret = false;
            try {
                //decimalformat.parse(txt.getText());
                if (txt.getName().equals("sumTxtPaidAmt")) {
                    sumPaidAmt = ((Number) decimalformat.parse(txt.getText())).doubleValue();
                    //txt.setText(decimalformat.format(sumPaidAmt));
                }
                if (txt.getName().equals("sumTxtCashAmt")) {
                    sumCashAmt = ((Number) decimalformat.parse(txt.getText())).doubleValue();
                }
                ret = true;
            } catch (ParseException ex) {
                Logger.getLogger(salesPanel.class.getName()).log(Level.SEVERE, null, ex);
                ret = false;
            }

            return ret;
        }
    };

    public void setParentJf(MainFrame parentJf) {
        this.parentJf = parentJf;
        sumTxtCashAmt.setInputVerifier(number_iv);
        sumTxtCashAmt.requestFocus();
        sumTxtNetAmt.setText(parentJf.getSpr().sumTxtNetAmount.getText());
        sumNetAmt = parentJf.getSpr().sumNetAmt;
        decimalformat = new DecimalFormat(parentJf.getMapVars().get("money_number"));
        dateformat = new SimpleDateFormat(parentJf.getMapVars().get("short_date_format"));

        load_list();
        sumCashAmt = sumNetAmt;
        sumTxtCashAmt.setText(decimalformat.format(sumCashAmt));
        sumTxtCashAmt.selectAll();

        try {
            PreparedStatement ps = parentJf.getSpr().dbConnection.prepareStatement("select INVOICETYPE.*,C_YCUST.NAME ACNAME "
                    + " from invoicetype,C_YCUST where C_YCUST.CODE(+)=INVOICETYPE.ACCNO AND location_code=? order by no", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ps.setString(1, parentJf.getSpr().dataLocationCode);
            ResultSet rsx = ps.executeQuery();
            rsx.beforeFirst();
            ((DefaultComboBoxModel) listType.getModel()).removeAllElements();
            while (rsx.next()) {
                ((DefaultComboBoxModel) listType.getModel()).addElement(new dataCell(rsx.getString("DESCR"), Double.valueOf(rsx.getDouble("NO"))));
            }
            ps.close();
            if (listType.getModel().getSize() <= 0) {
                throw new SQLException("No cash type found !");
            }
            listType.setSelectedIndex(0);
            varCashType = Double.valueOf(((dataCell) listType.getSelectedItem()).getValue().toString());
            if (parentJf.getMapVars().get("CASH_TYPE") != null) {
                varCashType = Integer.valueOf(parentJf.getMapVars().get("CASH_TYPE").toString());

            }
            sumTxtCashAmt.setEditable(false);
            listType.setEditable(false);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(parentJf, ex.getMessage());
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
//            if (varSelText.isEmpty()) {
//                throw new Exception("No reason of cancellation selected !");
//            }
            parentJf.getSpr().sumPaidAmt = sumPaidAmt;
            parentJf.getSpr().sumPaidAmt = sumPaidAmt;
            parentJf.getSpr().txtReasonCancel.setText(varSelText);
            parentJf.getSpr().close_voucher();


            setVisible(false);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(parentJf, ex.getMessage());
            Logger.getLogger(CloseVouDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox listType;
    private javax.swing.JPanel pnlParas1;
    private javax.swing.JPanel pnlSinglePay;
    private javax.swing.JPanel pnl_paras;
    private javax.swing.JTextField sumTxtCashAmt;
    private javax.swing.JLabel sumTxtNetAmt;
    // End of variables declaration//GEN-END:variables

    private void load_list() {
        pnl_paras.removeAll();
        Connection con = parentJf.getDbConneciton();
        try {
            PreparedStatement ps = con.prepareStatement("select INITCAP(Name) NAME "
                    + " from  relists where idlist='POS_CANCEL_REMARKS' "
                    + " ORDER BY POS", ResultSet.TYPE_SCROLL_INSENSITIVE,
                    ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = ps.executeQuery();
            if (rs == null || !rs.first()) {
                return;
            }
            rs.beforeFirst();
            GridBagConstraints gc = new GridBagConstraints();
            int i = 0;
            int i1 = 0;
            varSelText = "";
            while (rs.next()) {
                JRadioButton jr = new JRadioButton(rs.getString("NAME"));
                jr.setActionCommand(rs.getString("NAME"));
                jr.setFont(new Font("Dialog", Font.BOLD, 14));
                bg.add(jr);
                gc.gridx = i1;
                gc.gridy = i;
                gc.insets = new Insets(10, 10, 10, 10);
                gc.gridwidth = 1;
                gc.weightx = 0.0;
                gc.fill = GridBagConstraints.HORIZONTAL;
                pnl_paras.add(jr, gc);
                i = i + i1;
                i1 = (i1 == 0 ? 1 : 0);
                jr.addActionListener(new ActionListener() {

                    public void actionPerformed(ActionEvent e) {
                        varSelText = e.getActionCommand();
                    }
                });
            }
            ps.close();
            pnl_paras.updateUI();
        } catch (SQLException ex) {
            Logger.getLogger(closeReturnDlg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
