/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmSelReturned.java
 *
 * Created on May 2, 2014, 11:46:42 AM
 */
package com.forms.panels;

import com.forms.MainFrame;
import com.generic.model.localTableModel;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;

/**
 *
 * @author Yusuf
 */
public class frmSelReturned extends javax.swing.JDialog {

    private MainFrame parentJf = null;
    private double kf = -1;
    private Connection con = null;
    private localTableModel dataItems = new localTableModel();

    /** Creates new form frmSelReturned */
    public frmSelReturned(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        parentJf = (MainFrame) parent;
        setLocationRelativeTo(null);
    }

    public void OpenReturn(double kf) throws Exception {
        this.kf = kf;
        con = parentJf.getDbConneciton();

        if (dataItems.getDbclass() == null) {
            dataItems.createDBClassFromConnection(con);
        }
        show_return_items();
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlParas1 = new javax.swing.JPanel();
        pnl_paras = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        pnlParas1.setLayout(new java.awt.BorderLayout());

        pnl_paras.setLayout(new java.awt.GridBagLayout());
        pnlParas1.add(pnl_paras, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(pnlParas1);

        jButton1.setText("Generate Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Select all");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deselect All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Down");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Up");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        chkUnCheckAll(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        chkUnCheckAll(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        genReturn();
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getValue() + 50);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jScrollPane1.getVerticalScrollBar().getValue() > 40) {
            jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getValue() - 50);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public void genReturn() {
        parentJf.getCmdReturn().doClick();
        if (parentJf.cp != parentJf.getSpr()) {
            return;
        }
        parentJf.getSpr().load_data("");
        parentJf.getSpr().varSaleKeyfld = kf + "";
        for (int i = 0; i < dataItems.getRowCount(); i++) {
            boolean t = ((JCheckBox) dataItems.getFieldValue(i, "CHK")).isSelected();
            if (t) {
                try {
                    String itm = dataItems.getFieldValue(i, "REFER").toString();
                    String ctg = dataItems.getFieldValue(i, "SIZE_OF_DESCR").toString();
                    parentJf.getSpr().addUpdate(itm, ctg);
                } catch (Exception ex) {
                    Logger.getLogger(frmSelReturned.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        parentJf.getSpr().getJTable1().updateUI();

    }

    public void chkUnCheckAll(boolean t) {
        for (int i = 0; i < dataItems.getRowCount(); i++) {
            ((JCheckBox) dataItems.getFieldValue(i, "CHK")).setSelected(t);
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlParas1;
    private javax.swing.JPanel pnl_paras;
    // End of variables declaration//GEN-END:variables

    public void show_return_items() throws SQLException {
        pnl_paras.removeAll();
        GridBagConstraints gc = new GridBagConstraints();
        int i = 0;
        int i1 = 0;
        dataItems.executeQuery("select p2.itempos,p2.refer, p2.allqty/p2.pack pack_qty,"
                + " p2.size_of_descr,items.descr,'' chk from pospur2 p2,items "
                + " where reference=refer and p2.keyfld='" + kf
                + "' order by p2.itempos ", true);


        for (int j = 0; j < dataItems.getRowCount(); j++) {
            String s = j + " - " + dataItems.getFieldValue(j, "DESCR").toString() + " - "
                    + dataItems.getFieldValue(j, "SIZE_OF_DESCR").toString();
            JCheckBox jr = new JCheckBox(s);
            jr.setSelected(true);
            jr.setActionCommand(j + "");
            jr.setFont(new Font("Dialog", Font.BOLD, 14));
            gc.gridx = 0;
            gc.gridy = j;
            gc.insets = new Insets(10, 10, 10, 10);
            gc.gridwidth = 1;
            gc.weightx = 0.0;
            gc.fill = GridBagConstraints.HORIZONTAL;
            pnl_paras.add(jr, gc);
            dataItems.setFieldValue(j, "CHK", jr);
        }
        pnl_paras.updateUI();
    }
}
