/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShowMessageFrame.java
 *
 * Created on Apr 16, 2014, 10:13:41 AM
 */
package com.forms.panels;

import com.generic.utils.utils;
import java.awt.Font;
import java.awt.Window;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Yusuf
 */
public class ShowMessageFrame extends javax.swing.JFrame {

    private int delaystay = 0;
    private boolean on_exit_lost = false;
    public static final String RIGHT_BOTTOM = "RIGHT_BOTTOM";
    private String do_position = "CENTER";

    /** Creates new form ShowMessageFrame */
    public ShowMessageFrame(String msg, int fontsize, int timestay) {
        initComponents();
        setName("MSGW_" + System.currentTimeMillis());

        initMsg(msg, fontsize, timestay);
    }

    public ShowMessageFrame(String msg, int fontsize, int timestay, boolean exit_on_lost_focus) {
        initComponents();
        setName("MSGW_" + System.currentTimeMillis());
        this.on_exit_lost = exit_on_lost_focus;
        initMsg(msg, fontsize, timestay);
    }

    public ShowMessageFrame(String msg, int fontsize, int timestay, boolean exit_on_lost_focus, String location) {
        initComponents();
        setName("MSGW_" + System.currentTimeMillis());
        this.on_exit_lost = exit_on_lost_focus;
        this.do_position = location;
        initMsg(msg, fontsize, timestay);
    }

    public ShowMessageFrame(Exception ex, int fontsize, int timestay) {

        initComponents();
        setName("MSGW_" + System.currentTimeMillis());
        StringWriter sw = new StringWriter();
        ex.printStackTrace(new PrintWriter(sw));
        String stacktrace = sw.toString();
        initMsg(stacktrace, fontsize, timestay);
    }

    public static int closeAllWindows(String excl) {
        Window[] allWindows = Window.getWindows();
        int i = 0;
        for (i = 0; i < allWindows.length; i++) {
            if (allWindows[i].getName().startsWith("MSGW_") && !excl.equals(allWindows[i].getName())) {
                allWindows[i].setVisible(false);
            }
        }
        return i;
    }

    public void initMsg(String msg, int fontsize, int timestay) {
        closeAllWindows(getName());
        setResizable(false);
        jtext.setFont(new java.awt.Font("Dialog", Font.BOLD, fontsize)); // NOI18N``
        jtext.setContentType("text/plain");
        if (msg.toUpperCase().indexOf("<HTML>") >= 0) {
            jtext.setContentType("text/html");
        }
        jtext.setText(msg);
        if (do_position.equals(RIGHT_BOTTOM)) {
            double ry = getToolkit().getScreenSize().getWidth() - (getWidth() + 20);
            double rx = getToolkit().getScreenSize().getHeight() - (getHeight() + 20);
            setLocation(Double.valueOf(ry).intValue(), Double.valueOf(rx).intValue());
        }
        if (do_position.equals("CENTER")) {     
            setLocationRelativeTo(null);
        }
        setVisible(true);
        //setFocusable(on_exit_lost);
        setAlwaysOnTop(true);
        utils.parentJf.kf.setVisible(false);
        jtext.setCaretPosition(0);
        if (timestay < 0) {
            return;
        }
        delaystay = timestay;
        if (on_exit_lost) {
            addWindowFocusListener(new WindowFocusListener() {

                public void windowGainedFocus(WindowEvent e) {
                }

                public void windowLostFocus(WindowEvent e) {
                    //setVisible(false);
                }
            });
        }

        Timer tm = new Timer();
        tm.schedule(new TimerTask() {

            @Override
            public void run() {
                ShowMessageFrame.this.setVisible(false);
            }
        }, timestay);

        Timer tm1 = new Timer();
        tm1.schedule(new TimerTask() {

            @Override
            public void run() {
                delaystay = delaystay - 1000;
                if (delaystay < 0) {
                    cancel();
                } else {
                    lblTime.setText(Integer.valueOf(delaystay / 1000) + " Secs to close this window");
                }
            }
        }, 1000, 1000);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtext = new javax.swing.JEditorPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtext.setBackground(new java.awt.Color(-4144960,true));
        jScrollPane1.setViewportView(jtext);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(-4144960,true));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblTime.setText(" ");

        jButton2.setText("CLIPBOARD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(118, 118, 118)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jtext.selectAll();
        jtext.copy();
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane jtext;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
