/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * lovDialog.java
 *
 * Created on 22/04/2010, 07:01:36 م
 */
package com.forms;

import com.generic.model.DBClass;
import com.generic.utils.utils;
import com.lov.lovFrame;
import com.lov.selectListView;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.KeyStroke;

/**
 *
 * @author yusuf
 */
public class lovDialog extends javax.swing.JDialog implements lovFrame {

    /** Creates new form lovDialog */
    public lovDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        init();
    }

    public lovDialog(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        init();
    }

    private void init() {
        initComponents();
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,
                0, false);
        Action escapeAction = new AbstractAction() {

            public void actionPerformed(ActionEvent e) {
                setVisible(false);
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        slov.resize();
    }//GEN-LAST:event_formComponentResized

    @Override
    protected void finalize() throws Throwable {
        getRootPane().getActionMap().remove("ESCAPE");
        super.finalize();

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private selectListView slov = new selectListView();
    private DBClass dbc = null;
    private String sqlstr = "";
    private int selectedno = -1;
    private boolean can_select_multiple = false;
    private int NoOfClicksOnSelection = 0;

    public int getNoOfClicksOnSelection() {
        return NoOfClicksOnSelection;
    }

    public void setNoOfClicksOnSelection(int NoOfClicksOnSelection) {
        this.NoOfClicksOnSelection = NoOfClicksOnSelection;
    }

    public boolean isCan_select_multiple() {
        return can_select_multiple;
    }

    public void setCan_select_multiple(boolean can_select_multiple) {
        this.can_select_multiple = can_select_multiple;
    }

    public int getSelectedNo() {
        return this.selectedno;
    }

    public String getSqlstr() {
        return sqlstr;
    }

    public void setSqlstr(String sqlstn) {
        this.sqlstr = sqlstn;
    }

    public DBClass getDbc() {
        return dbc;
    }

    @Override
    public void setVisible(boolean b) {
        try {
            if (b) {
                selectedno = -1;
                setupLov();
            }
        } catch (SQLException ex) {
            Logger.getLogger(lovDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        super.setVisible(b);

    }

    public void setDbc(DBClass dbc) {

        this.dbc = dbc;
    }

    public selectListView getSlov() {
        return slov;
    }

    public void setupLov() throws SQLException {
        if (sqlstr != null && sqlstr.length() > 0) {
            dbc = slov.getLctb().createDBClassFromConnection(dbc.getDbConnection());
            slov.getLctb().executeQuery(sqlstr, true);
        }
        slov.getLctb().setEditAllowed(false);
        slov.setParentPanel(jPanel1);
        slov.setParentJf(this);
        slov.setSelectionStyle(2);
        slov.createView();
        repaint();
        setLocationRelativeTo(null);
    }

    public void setSelectedNo(int no) {
        this.selectedno = no;
        setVisible(false);
    }

    public void setwidth(int no) {
        setPreferredSize(new Dimension(no, getHeight()));
        pack();
    }

    public static lovDialog getInstance(String sql) throws SQLException {
        return getInstance(utils.getMainFrame(), sql, true, false);
    }

    public static lovDialog getInstance(Component par, String sql, int width, int height, boolean show, boolean auto_size_cols) throws SQLException {
        lovDialog ld = getInstance(par, sql, false, auto_size_cols);
        ld.getSlov().setAutoSize(auto_size_cols);
        ld.setSize(width, height);
        ld.setLocationRelativeTo(null);
        if (show) {
            ld.setVisible(true);
        }
        return ld;
    }

    public static lovDialog getInstance(Component par, String sql, boolean show, boolean auto_size_cols) throws SQLException {
        lovDialog ld = null;
        if (par instanceof Frame) {
            ld = new lovDialog((Frame) par, true);
        }
        if (par instanceof Dialog) {
            ld = new lovDialog((Dialog) par, true);
        }

        ld.getSlov().getLctb().createDBClassFromConnection(utils.getMainFrame().getDbConneciton());
        ld.setNoOfClicksOnSelection(selectListView.DOUBLE_CLICK_SELECTION);
        ld.getSlov().getLctb().executeQuery(sql, true);
        ld.getSlov().getLctb().setMasterRowsAsRows();
        if (show) {
            ld.setVisible(true);
        }
        return ld;
    }
}
